spring.application.name=nutrilis-server
server.port=8080
server.error.include-message=always
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
